---
- hosts: aoscx_switch1
  roles:
    - role: arubanetworks.aoscx_role
  vars:
    ansible_connection: network_cli
  gather_facts: false
  
  tasks:
   - name: Execute show version command
     aoscx_command:
      commands: ['show version']
     register: show_version_output
   - name: Output registered variable
     debug:
       var: show_version_output
