# Aruba AOSCX Playbook to show the current VLANs configure in the switch.

---
- hosts: aoscx_switch1
  roles:
    - role: arubanetworks.aoscx_role
  vars:
    ansible_connection: network_cli
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  
  tasks:
   - name: Show configured VLANs.
     aoscx_command:
      commands: ['show vlan']
     register: show_vlan_output
   - name: Output registered variable
     debug:
       var: show_vlan_output   

