## Working Playbook
## Displays on the screen the Aruba Switch Firmware Images of Primary and Secondary partition. 


---
- hosts: all
  roles:
    - role: arubanetworks.aoscx_role
  vars:
    ansible_connection: network_cli
    ansible_python_interpreter: /usr/bin/python3

  vars_files:
    - /etc/ansible/group_vars/aoscx_switches
 
  gather_facts: false
  
  tasks:
   - name: Execute show images command
     aoscx_command:
      commands: ['show images']
     register: show_images_output
   - name: Output registered variable
     debug:
       var: show_images_output   
