# Aruba AOSCX Playbook to reboot a switch.
---
- hosts: aoscx_switch1
  roles:
    - role: arubanetworks.aoscx_role
  
#  collections:
#    - arubanetworks.aos_switch

  vars:
    ansible_connection: network_cli
#    ansible_python_interpreter: /usr/bin/python3
 
  tasks:
    - name: Reboot Aruba Switch
      aoscx_command:
        commands:
          - command: 'boot system'
            prompt:
              - '.*\(y\/n\)\?.*'
            answer:
              -  y
