# Aruba AOSCX Playbook to upload a new firmware to a partition using TFTP.
---
- hosts: aoscx_switch1
  roles:
    - arubanetworks.aoscx_role
  vars:
    ansible_connection: network_cli
  gather_facts: false

  tasks:
    - name: Upload image to primary/secondary partition via TFTP.
      throttle: 10
      aoscx_command:
        commands:
          - command: 'copy tftp://x.x.x.x/ArubaOS-CX_x_x_x_x.swi secondary vrf default'
            prompt:
              - '.*\(y\/n\)\?.*'
            answer:
              -  y

