# Aruba AOSCX Playbook to update the password of the local admin account.

---
- hosts: aoscx_switch1
  roles:
    - role: arubanetworks.aoscx_role
  vars:
    ansible_connection: network_cli

  gather_facts: False
  tasks:
    - name: Update user login password
      aoscx_config:
         lines:
           - user admin password plaintext *****

