# Aruba AOSCX Playbook to reboot a switch to primary partition

---
- hosts: aoscx_switch1
  collections:
    - arubanetworks.aoscx
  gather_facts: False    
  tasks:
   - name: Boot the switch with the new image uploaded to primary partition.
     aoscx_boot_firmware:
       partition_name: 'primary'


